version: "3.7"
volumes:
  config:
  data:
    driver_opts:
      type: none
      device: ${MEDIA_PATH}
      o: bind
services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    logging:
      driver: journald
    network_mode: host
    restart: unless-stopped
    volumes:
      - config:/config
      - data:/data
